### ISSUE TITLE
Exception translation

### ISSUE THREAD

**Issue by rubenvincenten** [codeguy/Upload#57]
Would it be possible to implement translation for a future version?

**Comment by scottrobertson** [comment]
Not sure that is really the job of this library. You could catch them in your app and translate them there.

**Comment by rubenvincenten** [comment]
I suppose it's not possible to extend \Upload\Exception for each validation so each exception can have it's on class name? You could add an array to Codeguy\Upload where validation exceptions are stored, or extract a part of isValid() so programmer's can wrap it in their own try/catchblock.
