### ISSUE TITLE
Cannot find uploaded file identified by key:

### ISSUE THREAD

**Issue by raisiqueira** [codeguy/Upload#58]
i have a code:

$arquivo = $app->request()->post('teste');
	$local = ROOT."public" . DS . "media" . DS;
	$storage = new \Upload\Storage\FileSystem($local);
	$file = new \Upload\File($arquivo, $storage);

this return the message: Cannot find uploaded file identified by key:

**Comment by nmpribeiro** [comment]
Did you solve it?

**Comment by brandonsavage** [comment]
This appears to be something you're doing in your code. It's not something I'll be able to fix for you.
